#!/bin/bash
echo -e "Local Variables:\n$(compgen -v | while read var; do if [[ $var != BASH_* && $var != FUNCNAME && $var != var ]]; then echo "$var=${!var}"; fi done)\nEnvironment Variables:\n$(printenv | sort)\nFunctions:\n$(declare -F | while read func; do echo ${func#*_}; done)"
